name: redarx_ng_example
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.2.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  redarx:
    #path: /Users/Me/projects/tools/redarx
    git:
      url: git://github.com/rxlabz/redarx
      ref: v0.5.0
transformers:
- angular2:
    resolved_indentifiers:
      Dispatcher: "package:redarx/redarx.dart"
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
